# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestU2():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_u2(self):
    self.driver.get("https://www.zhipin.com/web/geek/jobs?query=&city=101280100&position=100101")
    self.driver.set_window_size(550, 696)
    element = self.driver.find_element(By.LINK_TEXT, "海归")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".expect-item:nth-child(2) > .text-content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".card-area:nth-child(2) .job-info").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card-area:nth-child(3) .job-info").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card-area:nth-child(4) .job-info").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".active .boss-name")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".card-area:nth-child(5) .job-info").click()
  
